# o arquivo kustomization é o ponto de entrada para a geração
# da descrição dos recursos k8s que serão criados
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# indica onde o kustomize irá aplicar a customização atual
# ou seja, primeiro leva em consideração o que está escrito lá
# ele procura um arquivo kustomization que está lá e seguirá o caminho
# indicado no resources daquele kustomization, achando a base
- ../../base/sales/

# patches acrescentam/modificam declarações no arquivo base
patches:
- path: ./dev-sales-patch-deploy.yaml
- path: ./dev-sales-patch-service.yaml

# altera o nome da imagem no arquivo base
images:
- name: service-image
  newName: vitoraalmeida/service/sales-api
  newTag: 0.0.1
