# esse arquivo de especificação do k8s é uma base comum
# a todos os deployments relacionados ao serviço sales
# O kustomize irá manter o que não for alterado por algum
# arquivo de customização que for declarado.
# Assim podemos manter uma base comum a todos os ambientes
# e apenas diferenciar o que for específico para cada ambiente
apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    # label que nos permite buscar pelo deployment por um nome
    matchLabels:
      app: sales

  template:
    metadata:
      labels:
        app: sales

    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: sales-api
        # a imagem é passada durante a customização (kustomize)
        image: service-image # placeholder

        # GOMAXPROCS vai ser igual ao valor definido no limits para esse deploy
        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              # se o valor não for exato, ele arredonda pra cima
              # 1500m cpu -> 1.5 -> GOMAXPROCS = 2
              resource: limits.cpu
